### ISSUE TITLE
Ubuntu 12 Python 2.7.3 issue

### ISSUE THREAD

**Issue by muskox** [codeforanchorage/moa_property_tax_geojson#2]
Hi Hans,

I followed the instructions and I get this:

in the virtualenv I run: pip install -r requirements.txt

```
Downloading/unpacking pymongo==3.0.1 (from -r requirements.txt (line 1))
  Downloading pymongo-3.0.1.tar.gz (381Kb): 381Kb downloaded
  Running setup.py egg_info for package pymongo

Downloading/unpacking GDAL==1.11.2 (from -r requirements.txt (line 2))
  Downloading GDAL-1.11.2.tar.gz (477Kb): 477Kb downloaded
  Running setup.py egg_info for package GDAL

    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/spustay/gits/moa_property_tax_geojson/venv/build/GDAL/setup.py", line 301, in <module>
        **extra )
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 12, in replacement_run
      File "/home/spustay/gits/moa_property_tax_geojson/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/egg_info.py", line 254, in find_sources
        mm.run()
      File "/home/spustay/gits/moa_property_tax_geojson/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/egg_info.py", line 308, in run
        self.add_defaults()
      File "/home/spustay/gits/moa_property_tax_geojson/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/egg_info.py", line 332, in add_defaults
        sdist.add_defaults(self)
      File "/home/spustay/gits/moa_property_tax_geojson/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/sdist.py", line 191, in add_defaults
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/home/spustay/gits/moa_property_tax_geojson/venv/build/GDAL/setup.py", line 196, in finalize_options
        self.gdaldir = self.get_gdal_config('prefix')
      File "/home/spustay/gits/moa_property_tax_geojson/venv/build/GDAL/setup.py", line 176, in get_gdal_config
        return fetch_config(option)
      File "/home/spustay/gits/moa_property_tax_geojson/venv/build/GDAL/setup.py", line 129, in fetch_config
        raise gdal_config_error, e""")
      File "<string>", line 4, in <module>
    __main__.gdal_config_error: [Errno 2] No such file or directory
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/GDAL.egg-info

writing pip-egg-info/GDAL.egg-info/PKG-INFO

writing top-level names to pip-egg-info/GDAL.egg-info/top_level.txt

writing dependency_links to pip-egg-info/GDAL.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/GDAL.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/spustay/gits/moa_property_tax_geojson/venv/build/GDAL/setup.py", line 301, in <module>

    **extra )

  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "<string>", line 12, in replacement_run

  File "/home/spustay/gits/moa_property_tax_geojson/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/egg_info.py", line 254, in find_sources

    mm.run()

  File "/home/spustay/gits/moa_property_tax_geojson/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/egg_info.py", line 308, in run

    self.add_defaults()

  File "/home/spustay/gits/moa_property_tax_geojson/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/egg_info.py", line 332, in add_defaults

    sdist.add_defaults(self)

  File "/home/spustay/gits/moa_property_tax_geojson/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/sdist.py", line 191, in add_defaults

    build_ext = self.get_finalized_command('build_ext')

  File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command

    cmd_obj.ensure_finalized()

  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "/home/spustay/gits/moa_property_tax_geojson/venv/build/GDAL/setup.py", line 196, in finalize_options

    self.gdaldir = self.get_gdal_config('prefix')

  File "/home/spustay/gits/moa_property_tax_geojson/venv/build/GDAL/setup.py", line 176, in get_gdal_config

    return fetch_config(option)

  File "/home/spustay/gits/moa_property_tax_geojson/venv/build/GDAL/setup.py", line 129, in fetch_config

    raise gdal_config_error, e""")

  File "<string>", line 4, in <module>

__main__.gdal_config_error: [Errno 2] No such file or directory

----------------------------------------
```

I'll take a look at what the issue.

Scott

**Comment by thermokarst** [comment]
Hi @muskox! GDAL doesn't play well with virtualenv, the requirements.txt probably needs to be updated to use something like `pygdal` instead of `gdal`. That might be a good starting point for your investigations. pygdal is a virtualenv-friendly gdal wrapper.

_edit_: fixed auto-correct typo

**Comment by hansthompson** [comment]
Cool. I was starting to look at used macbooks on craigslist to play with this problem. I'll hold off for a bit. :)

**Comment by thermokarst** [comment]
Closing stale issue. We can address at a later date if needed.
